name: lpe_sdk_example
description: Example app showcasing Learmond Pay Element (LPE) SDK
publish_to: none
version: 0.0.1
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  lpe_sdk:
    path: ..
  flutter_inappwebview: ^6.0.0
  http: ^0.13.0

flutter:
  uses-material-design: true
